// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtQavsP28MuJ-rn6FXsUMStTqwqQpmjS8',
    appId: '1:852125964298:web:d12d7fff0dbd1f3e2127f3',
    messagingSenderId: '852125964298',
    projectId: 'astro-d7619',
    authDomain: 'astro-d7619.firebaseapp.com',
    storageBucket: 'astro-d7619.appspot.com',
    measurementId: 'G-TF1F6ZKQKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqF6px2t0y-fpiczX3MlfZnGyYLYgg78Q',
    appId: '1:852125964298:android:0bc812ccf9f993e02127f3',
    messagingSenderId: '852125964298',
    projectId: 'astro-d7619',
    storageBucket: 'astro-d7619.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAekjQGtNh23GI_Zt8bKjvZZjWs2T1W7A',
    appId: '1:852125964298:ios:0b39d571cf93eff52127f3',
    messagingSenderId: '852125964298',
    projectId: 'astro-d7619',
    storageBucket: 'astro-d7619.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAekjQGtNh23GI_Zt8bKjvZZjWs2T1W7A',
    appId: '1:852125964298:ios:0b39d571cf93eff52127f3',
    messagingSenderId: '852125964298',
    projectId: 'astro-d7619',
    storageBucket: 'astro-d7619.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtQavsP28MuJ-rn6FXsUMStTqwqQpmjS8',
    appId: '1:852125964298:web:2af915a592494ded2127f3',
    messagingSenderId: '852125964298',
    projectId: 'astro-d7619',
    authDomain: 'astro-d7619.firebaseapp.com',
    storageBucket: 'astro-d7619.appspot.com',
    measurementId: 'G-M2SBKRYT50',
  );
}
